// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Penitenciaria.Datos;

#nullable disable

namespace Penitenciaria.Migrations
{
    [DbContext(typeof(PenitenciariaDbContext))]
    [Migration("20251126220029_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Penitenciaria.Modelos.Celda", b =>
                {
                    b.Property<int>("CeldaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CeldaID"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("NumeroCelda")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OcupacionActual")
                        .HasColumnType("int");

                    b.HasKey("CeldaID");

                    b.HasIndex("NumeroCelda")
                        .IsUnique();

                    b.ToTable("Celdas");
                });

            modelBuilder.Entity("Penitenciaria.Modelos.Crimen", b =>
                {
                    b.Property<int>("CrimenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrimenID"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCrimen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PenaMaximaAnios")
                        .HasColumnType("int");

                    b.Property<int?>("PenaMinimaAnios")
                        .HasColumnType("int");

                    b.HasKey("CrimenID");

                    b.HasIndex("NombreCrimen")
                        .IsUnique();

                    b.ToTable("Crimenes");
                });

            modelBuilder.Entity("Penitenciaria.Modelos.Reo", b =>
                {
                    b.Property<int>("ReoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReoID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CeldaID")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SentenciaTotalAnios")
                        .HasColumnType("int");

                    b.HasKey("ReoID");

                    b.HasIndex("CeldaID");

                    b.ToTable("Reos");
                });

            modelBuilder.Entity("Penitenciaria.Modelos.ReoCrimen", b =>
                {
                    b.Property<int>("ReoCrimenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReoCrimenID"));

                    b.Property<int>("CrimenID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaComision")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReoID")
                        .HasColumnType("int");

                    b.HasKey("ReoCrimenID");

                    b.HasIndex("CrimenID");

                    b.HasIndex("ReoID", "CrimenID")
                        .IsUnique();

                    b.ToTable("ReoCrimenes");
                });

            modelBuilder.Entity("Penitenciaria.Modelos.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Empleado"
                        });
                });

            modelBuilder.Entity("Penitenciaria.Modelos.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioID"));

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiracionTokenRefresco")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiracionTokenReinicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("TokenConfirmacionEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenRefresco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenReinicioContrasena")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioID");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Penitenciaria.Modelos.Reo", b =>
                {
                    b.HasOne("Penitenciaria.Modelos.Celda", "Celda")
                        .WithMany("Reos")
                        .HasForeignKey("CeldaID");

                    b.Navigation("Celda");
                });

            modelBuilder.Entity("Penitenciaria.Modelos.ReoCrimen", b =>
                {
                    b.HasOne("Penitenciaria.Modelos.Crimen", "Crimen")
                        .WithMany("ReoCrimenes")
                        .HasForeignKey("CrimenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Penitenciaria.Modelos.Reo", "Reo")
                        .WithMany("ReoCrimenes")
                        .HasForeignKey("ReoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crimen");

                    b.Navigation("Reo");
                });

            modelBuilder.Entity("Penitenciaria.Modelos.Usuario", b =>
                {
                    b.HasOne("Penitenciaria.Modelos.Rol", "Rol")
                        .WithMany("Usuario")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Penitenciaria.Modelos.Celda", b =>
                {
                    b.Navigation("Reos");
                });

            modelBuilder.Entity("Penitenciaria.Modelos.Crimen", b =>
                {
                    b.Navigation("ReoCrimenes");
                });

            modelBuilder.Entity("Penitenciaria.Modelos.Reo", b =>
                {
                    b.Navigation("ReoCrimenes");
                });

            modelBuilder.Entity("Penitenciaria.Modelos.Rol", b =>
                {
                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
